
# Levels: TRACE, DEBUG, INFO, WARN, ERROR and FATAL

# Set root logger level to DEBUG and its only appender to A1.
log4j.rootLogger=ERROR, A1

# A1 is set to be a ConsoleAppender.
log4j.appender.A1=org.apache.log4j.ConsoleAppender

# A1 uses PatternLayout.
log4j.appender.A1.layout=org.apache.log4j.PatternLayout
log4j.appender.A1.layout.ConversionPattern=%-4r [%t] %-5p %c %x - %m%n

# org.opendap.d1 is far more verbose...
log4j.logger.org.opendap.d1=DEBUG, R

log4j.appender.R=org.apache.log4j.FileAppender
log4j.appender.R.File=opendap.log

# These were used when R was a RollingFileAppender. jhrg 5/20/14
#log4j.appender.R.MaxFileSize=100KB
# Keep one backup file
#log4j.appender.R.MaxBackupIndex=1

# R uses PatternLayout.
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%-5p [%F:%L] - %m%n
